name: build
on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 15
      - name: install dependencies
        run: |
          npm install -g pnpm
          npm run pnpm-install
      - name: check code style
        run: npm run lint && [[ $(git status --porcelain | tee >(cat 1>&2) | wc -l) -eq 0 ]]
      - run: npm run build
      - name: prepare demo site
        run: |
          cp content/demo.json dist/content.json
          echo 'https://ndnts-video.netlify.app/* https://ndnts-video.ndn.today/:splat 301!' > dist/_redirects
      - uses: South-Paw/action-netlify-deploy@v1.0.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: c8f329f1-251e-4a13-8961-b4d746003a2b
          build-dir: ./dist/
        if: ${{ github.repository == 'yoursunny/NDNts-video' && github.event_name == 'push' }}
      - name: prepare pushups site
        run: |
          cp content/pushups.json dist/content.json
          echo 'https://pushups.netlify.app/* https://pushups.ndn.today/:splat 301!' > dist/_redirects
      - uses: South-Paw/action-netlify-deploy@v1.0.4
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          netlify-auth-token: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          netlify-site-id: 6d2a1eee-af73-45a9-8f35-f446403acf76
          build-dir: ./dist/
        if: ${{ github.repository == 'yoursunny/NDNts-video' && github.event_name == 'push' }}
